#!/usr/bin/env sh

docker build -t local/c8-systemd c8-systemd
docker build -t local/o2-aliceo2 o2-aliceo2

docker volume create --name vc_o2dock_sw

docker run -it --rm -v vc_o2dock_sw:/alice local/o2-aliceo2 /root/bootstrap.sh
