# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
          . /etc/bashrc
          fi

alias enter-spack='. /opt/spack/share/spack/setup-env.sh'
